import Foundation

enum AppLanguage: String, Codable, CaseIterable {
    case zh
    case en

    var locale: Locale { Locale(identifier: self == .zh ? "zh_CN" : "en_US") }
    var toggleLabel: String { "En / 中" }
    var accessibilityToggle: String { self == .zh ? "切换为 English" : "Switch to Chinese" }
}

enum Copy {
    private static let values: [String: [AppLanguage: String]] = [
        "openRaf": [.zh: "导入 RAF…", .en: "Import RAF…"],
        "settings": [.zh: "设置", .en: "Settings"],
        "close": [.zh: "关闭", .en: "Close"],
        "convertRaw": [.zh: "转换 RAW", .en: "Convert RAW"],
        "selectRaf": [.zh: "选择 RAF", .en: "Select RAF"],
        "dropRaf": [.zh: "拖放一个或多个文件，或点按选择", .en: "Drop one or more files, or click to choose"],
        "files": [.zh: "个文件", .en: "files"],
        "filesSelected": [.zh: "个 RAF 已选择", .en: "RAFs selected"],
        "clearSelection": [.zh: "清空选择", .en: "Clear selection"],
        "whiteBalance": [.zh: "白平衡", .en: "White balance"],
        "auto": [.zh: "自动", .en: "Auto"],
        "asShot": [.zh: "拍摄值", .en: "As shot"],
        "donor": [.zh: "供体", .en: "Donor"],
        "distortion": [.zh: "畸变", .en: "Distortion"],
        "distortionModel": [.zh: "畸变模型", .en: "Distortion model"],
        "cameraJpegMatch": [.zh: "机内 JPEG 匹配", .en: "Camera JPEG match"],
        "nativeMatch": [.zh: "厂商 RAW 匹配", .en: "Vendor RAW match"],
        "legacyInBounds": [.zh: "旧版无空边", .en: "Legacy no-blank-edge"],
        "distortionModelDetail": [
            .zh: "机内 JPEG 匹配是默认方案；厂商 RAW 匹配保留 0.9.5 原方案；旧版无空边保留 0.9.3 几何。关闭畸变仍表示完全不矫正",
            .en: "Camera JPEG match is the default. Vendor RAW match preserves the 0.9.5 method; Legacy no-blank-edge preserves 0.9.3 geometry. Turning Distortion off applies no correction",
        ],
        "ca": [.zh: "色差", .en: "Chromatic aberration"],
        "vignetting": [.zh: "暗角", .en: "Vignetting"],
        "captureDetails": [.zh: "拍摄信息", .en: "Capture details"],
        "loadingCapture": [.zh: "正在读取 RAF", .en: "Reading RAF"],
        "captureUnavailable": [.zh: "无法读取拍摄信息", .en: "Capture details unavailable"],
        "shutter": [.zh: "快门", .en: "Shutter"],
        "aperture": [.zh: "光圈", .en: "Aperture"],
        "focalLength": [.zh: "焦距", .en: "Focal length"],
        "exposureCompensation": [.zh: "曝光补偿", .en: "Exposure comp."],
        "resolution": [.zh: "有效尺寸", .en: "Active size"],
        "convert3fr": [.zh: "转换为 3FR", .en: "Convert to 3FR"],
        "convertBatch": [.zh: "批量转换为 3FR", .en: "Convert batch to 3FR"],
        "cancel": [.zh: "取消", .en: "Cancel"],
        "currentJob": [.zh: "当前任务", .en: "Current job"],
        "recent": [.zh: "最近结果", .en: "Recent"],
        "ready": [.zh: "准备就绪", .en: "Ready"],
        "selected": [.zh: "已选择", .en: "Selected"],
        "converting": [.zh: "正在转换", .en: "Converting"],
        "verifying": [.zh: "正在核验", .en: "Verifying"],
        "complete": [.zh: "转换完成", .en: "Complete"],
        "failed": [.zh: "转换失败", .en: "Failed"],
        "cancelled": [.zh: "已取消", .en: "Cancelled"],
        "selectToStart": [.zh: "选择 RAF 开始转换", .en: "Select a RAF to begin"],
        "reveal": [.zh: "在 Finder 中显示", .en: "Show in Finder"],
        "openPhocus": [.zh: "在 Phocus 中打开", .en: "Open in Phocus"],
        "show": [.zh: "显示", .en: "Show"],
        "x2dContainer": [.zh: "X2D 容器", .en: "X2D container"],
        "notConfigured": [.zh: "未设置", .en: "Not configured"],
        "currentSource": [.zh: "当前模板", .en: "Current template"],
        "bundledSanitized": [.zh: "内置净化模板", .en: "Built-in sanitized template"],
        "externalOverride": [.zh: "外部覆盖", .en: "External override"],
        "chooseExternalEllipsis": [.zh: "选择外部模板…", .en: "Choose external template…"],
        "restoreBundled": [.zh: "恢复内置净化模板", .en: "Restore built-in sanitized template"],
        "bundledDonorMissing": [.zh: "内置 X2D 模板缺失，请重新安装应用", .en: "Built-in X2D template is missing. Reinstall the app."],
        "bundledDonorUnreadable": [.zh: "无法读取内置 X2D 模板，请重新安装应用", .en: "Built-in X2D template cannot be read. Reinstall the app."],
        "bundledDonorCorrupt": [.zh: "内置 X2D 模板校验失败，请重新安装应用", .en: "Built-in X2D template failed verification. Reinstall the app."],
        "chooseEllipsis": [.zh: "选择…", .en: "Choose…"],
        "replaceEllipsis": [.zh: "更换…", .en: "Replace…"],
        "processing": [.zh: "处理方式", .en: "Processing"],
        "sensorMapping": [.zh: "传感器映射", .en: "Sensor mapping"],
        "adaptive": [.zh: "光源自适应", .en: "Illuminant adaptive"],
        "donorLens": [.zh: "供体镜头数据", .en: "Donor lens data"],
        "neutralize": [.zh: "中和", .en: "Neutralize"],
        "preserve": [.zh: "保留", .en: "Preserve"],
        "inverse": [.zh: "FFF 增益反向补偿", .en: "Reverse FFF gain"],
        "isoPolicy": [.zh: "ISO 映射", .en: "ISO mapping"],
        "isoNearest": [.zh: "邻近 X2D 档位", .en: "Nearest X2D value"],
        "isoHnnrStable": [.zh: "HNNR 安全（最高 6400）", .en: "HNNR safe (max 6400)"],
        "isoCapture": [.zh: "保留富士拍摄值", .en: "Preserve Fujifilm value"],
        "isoPolicyDetail": [
            .zh: "使用 HNNR 时请选择安全模式；邻近档位与保留拍摄值不保证降噪兼容。拍摄 ISO 始终保留在记录中",
            .en: "Use HNNR-safe for HNNR; Nearest and Capture do not guarantee denoise compatibility. Capture ISO remains in the record",
        ],
        "exposurePolicy": [.zh: "默认曝光", .en: "Default exposure"],
        "exposureMatchFujifilm": [.zh: "匹配富士渲染", .en: "Match Fujifilm rendering"],
        "exposurePreserveRaw": [.zh: "保留线性 RAW", .en: "Preserve linear RAW"],
        "exposurePolicyDetail": [
            .zh: "默认读取每张 RAF 的曝光偏置并写入 Phocus 调整；不会放大或裁切 RAW 数据",
            .en: "Uses each RAF's exposure bias in Phocus without scaling or clipping the RAW payload",
        ],
        "phocusCompensation": [.zh: "Phocus 曝光", .en: "Phocus exposure"],
        "phocusRendering": [.zh: "Phocus 渲染", .en: "Phocus rendering"],
        "dynamicRangeMigration": [.zh: "迁移动态范围", .en: "Migrate dynamic range"],
        "dynamicRangeMigrationDetail": [
            .zh: "DR100 / 200 / 400 映射高光恢复；D 范围优先会额外映射阴影填充，不改动线性 RAW",
            .en: "Maps DR100 / 200 / 400 to highlight recovery; D Range Priority also maps shadow fill without changing linear RAW",
        ],
        "toneCurveMigration": [.zh: "迁移高光与阴影曲线", .en: "Migrate highlight and shadow tone"],
        "grainMigration": [.zh: "迁移胶片颗粒", .en: "Migrate film grain"],
        "colorRenderingMigration": [.zh: "迁移色彩强度", .en: "Migrate color intensity"],
        "contrastRenderingMigration": [.zh: "迁移全局反差", .en: "Migrate global contrast"],
        "clarityRenderingMigration": [.zh: "迁移清晰度", .en: "Migrate clarity"],
        "sharpnessRenderingMigration": [.zh: "迁移锐度", .en: "Migrate sharpness"],
        "monochromeRenderingMigration": [.zh: "迁移黑白意图", .en: "Migrate monochrome intent"],
        "creativeMigrationDetail": [
            .zh: "按富士相机档位单调映射到可逆的 Phocus 全局调整",
            .en: "Monotonically maps Fujifilm camera steps to reversible global Phocus adjustments",
        ],
        "sharpnessMigrationDetail": [
            .zh: "使用保守 USM 映射，并保持 Phocus 强制降噪路径关闭",
            .en: "Uses a conservative USM mapping while keeping Phocus forced-noise paths disabled",
        ],
        "monochromeMigrationDetail": [
            .zh: "迁移中性黑白；滤镜与冷暖色调原值仍保留在元数据中",
            .en: "Migrates neutral monochrome; filter and toning intent remains recorded in metadata",
        ],
        "approximateMigrationDetail": [
            .zh: "近似映射，默认开启；可随时在 Phocus 中调整或移除",
            .en: "Approximate mapping, on by default; remains editable and removable in Phocus",
        ],
        "dynamicRange": [.zh: "动态范围", .en: "Dynamic range"],
        "toneCurve": [.zh: "高光 / 阴影", .en: "Highlight / shadow"],
        "grain": [.zh: "颗粒", .en: "Grain"],
        "metadata": [.zh: "完整元数据", .en: "Full metadata"],
        "metadataMigration": [.zh: "元数据迁移", .en: "Metadata migration"],
        "framingMigration": [.zh: "迁移构图与画幅", .en: "Migrate framing and aspect ratio"],
        "framingMigrationDetail": [
            .zh: "将画幅比例和数码增距构图写为可逆的 Phocus 裁切",
            .en: "Writes aspect ratio and Digital Tele-Conv framing as a reversible Phocus crop",
        ],
        "locationMigration": [.zh: "保留拍摄位置", .en: "Preserve capture location"],
        "locationMigrationDetail": [
            .zh: "将 RAF 中存在的 GPS 坐标与海拔迁移到标准 XMP",
            .en: "Migrates GPS coordinates and altitude from the RAF into standard XMP",
        ],
        "rightsMigration": [.zh: "保留评分与著作信息", .en: "Preserve rating and rights"],
        "rightsMigrationDetail": [
            .zh: "迁移评分、作者、版权与用户注释；不存在时不会补造",
            .en: "Migrates rating, creator, copyright and comment only when present",
        ],
        "provenanceMigration": [.zh: "保留富士来源记录", .en: "Preserve Fujifilm provenance"],
        "provenanceMigrationDetail": [
            .zh: "记录原机型、固件与源文件名，不改变用于 Phocus 识别的哈苏机型",
            .en: "Records original camera, firmware and source name without changing Hasselblad routing identity",
        ],
        "capture": [.zh: "拍摄", .en: "Capture"],
        "fujifilmRendering": [.zh: "富士渲染意图", .en: "Fujifilm rendering intent"],
        "framing": [.zh: "构图", .en: "Framing"],
        "cameraState": [.zh: "相机状态", .en: "Camera state"],
        "fileAndProvenance": [.zh: "文件与来源", .en: "File and provenance"],
        "filmSimulation": [.zh: "胶片模拟", .en: "Film simulation"],
        "color": [.zh: "色彩", .en: "Color"],
        "colorChrome": [.zh: "彩色效果", .en: "Color Chrome"],
        "colorChromeBlue": [.zh: "蓝色彩色效果", .en: "Color Chrome Blue"],
        "clarity": [.zh: "清晰度", .en: "Clarity"],
        "sharpness": [.zh: "锐度", .en: "Sharpness"],
        "highIsoNoiseReduction": [.zh: "高 ISO 降噪", .en: "High ISO noise reduction"],
        "contrast": [.zh: "反差", .en: "Contrast"],
        "aspectRatio": [.zh: "画幅比例", .en: "Aspect ratio"],
        "digitalTeleconverter": [.zh: "数码增距", .en: "Digital Tele-Conv"],
        "orientation": [.zh: "方向", .en: "Orientation"],
        "location": [.zh: "位置", .en: "Location"],
        "altitude": [.zh: "海拔", .en: "Altitude"],
        "rating": [.zh: "评分", .en: "Rating"],
        "artist": [.zh: "作者", .en: "Creator"],
        "copyright": [.zh: "版权", .en: "Copyright"],
        "comment": [.zh: "注释", .en: "Comment"],
        "shutterType": [.zh: "快门类型", .en: "Shutter type"],
        "focusMode": [.zh: "对焦模式", .en: "Focus mode"],
        "afMode": [.zh: "自动对焦区域", .en: "AF mode"],
        "focusPoint": [.zh: "对焦点", .en: "Focus point"],
        "driveMode": [.zh: "驱动模式", .en: "Drive mode"],
        "cameraAttitude": [.zh: "机身姿态", .en: "Camera attitude"],
        "sourceEncoding": [.zh: "源 RAW 编码", .en: "Source RAW encoding"],
        "firmware": [.zh: "固件", .en: "Firmware"],
        "sourceFile": [.zh: "源文件", .en: "Source file"],
        "sourceCamera": [.zh: "来源相机", .en: "Source camera"],
        "fileSize": [.zh: "文件大小", .en: "File size"],
        "created": [.zh: "创建时间", .en: "Created"],
        "modified": [.zh: "修改时间", .en: "Modified"],
        "gpsTime": [.zh: "GPS 时间", .en: "GPS time"],
        "monochromeTone": [.zh: "黑白色调", .en: "Monochrome tone"],
        "lensModulationOptimizer": [.zh: "镜头优化调制器", .en: "Lens modulation optimizer"],
        "flashCompensation": [.zh: "闪光补偿", .en: "Flash compensation"],
        "flickerReduction": [.zh: "闪烁抑制", .en: "Flicker reduction"],
        "captureWarnings": [.zh: "拍摄警告", .en: "Capture warnings"],
        "compositeCapture": [.zh: "合成拍摄", .en: "Composite capture"],
        "active": [.zh: "启用", .en: "Active"],
        "inactive": [.zh: "未启用", .en: "Inactive"],
        "none": [.zh: "无", .en: "None"],
        "yes": [.zh: "是", .en: "Yes"],
        "no": [.zh: "否", .en: "No"],
        "off": [.zh: "关闭", .en: "Off"],
        "weak": [.zh: "弱", .en: "Weak"],
        "strong": [.zh: "强", .en: "Strong"],
        "small": [.zh: "小", .en: "Small"],
        "large": [.zh: "大", .en: "Large"],
        "hardwareUtilization": [.zh: "硬件利用率", .en: "Hardware utilisation"],
        "hardwareEfficiency": [.zh: "节能", .en: "Efficiency"],
        "hardwareBalanced": [.zh: "均衡", .en: "Balanced"],
        "hardwarePerformance": [.zh: "高性能", .en: "Performance"],
        "parallelJobs": [.zh: "个并行任务", .en: "parallel jobs"],
        "threadsPerJob": [.zh: "线程/任务", .en: "threads/job"],
        "parallelTaskLimit": [.zh: "允许并行的任务数量", .en: "Parallel task limit"],
        "cpuCoreLimit": [.zh: "CPU 核心上限", .en: "CPU core limit"],
        "memoryLimit": [.zh: "RAM 调度预算", .en: "RAM scheduling budget"],
        "jobs": [.zh: "任务", .en: "jobs"],
        "cores": [.zh: "核心", .en: "cores"],
        "effectiveJobs": [.zh: "个实际并行任务", .en: "effective parallel jobs"],
        "ramBudgetDetail": [
            .zh: "用于限制同时运行的任务；单个 RAW 的实际峰值由图像内容决定",
            .en: "Limits simultaneous jobs; a single RAW's peak still depends on image content",
        ],
        "physicalExtraVignette": [.zh: "物理额外暗角", .en: "Physical extra vignette"],
        "skipExtraVignette": [.zh: "跳过额外暗角", .en: "Skip extra vignette"],
        "negativeVignetteCompatibility": [
            .zh: "全平面 CFA 模型保持自然噪声尺度；也可选择不写入额外暗角。",
            .en: "Full-plane CFA modelling preserves natural noise scale; extra vignette can also be skipped.",
        ],
        "batchProcessing": [.zh: "批量处理中", .en: "Batch processing"],
        "processingActive": [.zh: "处理中", .en: "Processing"],
        "batchComplete": [.zh: "个文件完成", .en: "files complete"],
        "batchFailed": [.zh: "个失败", .en: "failed"],
        "conversionMenu": [.zh: "转换", .en: "Convert"],
        "startConversion": [.zh: "开始转换", .en: "Start conversion"],
        "chooseRafPanel": [.zh: "选择一个或多个 GFX 100RF RAF", .en: "Choose one or more GFX 100RF RAFs"],
        "chooseOutputFolder": [.zh: "选择批量 3FR 输出文件夹", .en: "Choose the batch 3FR output folder"],
        "outputExists": [.zh: "输出文件或转换记录已存在，请选择新名称", .en: "The output or conversion record already exists. Choose a new name."],
        "chooseDonorPanel": [.zh: "选择 X2D 100C 3FR", .en: "Choose an X2D 100C 3FR"],
        "invalidRaf": [.zh: "请选择 RAF 文件", .en: "Choose a RAF file"],
        "invalidDonor": [.zh: "请选择 3FR 文件", .en: "Choose a 3FR file"],
        "permissionError": [.zh: "无法保存容器访问权限", .en: "Unable to save container access"],
        "convertingFile": [.zh: "正在转换", .en: "Converting"],
        "verifyingFile": [.zh: "正在核验 3FR", .en: "Verifying 3FR"],
        "engineUnavailable": [.zh: "转换引擎不可用", .en: "Conversion engine unavailable"],
        "engineFailed": [.zh: "转换引擎失败", .en: "Conversion engine failed"],
        "notifications": [.zh: "完成时通知", .en: "Completion notification"],
        "notificationTitle": [.zh: "3FR 已完成", .en: "3FR complete"],
        "notificationDenied": [.zh: "通知权限未开启", .en: "Notifications are not allowed"],
    ]

    static func text(_ key: String, _ language: AppLanguage) -> String {
        values[key]?[language] ?? key
    }
}
