package com.raf3fr.app.model

data class ProductCopy(
    val settings: String,
    val chooseRaf: String,
    val replaceRaf: String,
    val sourceHint: String,
    val donor: String,
    val donorMissing: String,
    val chooseDonor: String,
    val bundledSanitized: String,
    val useBundled: String,
    val whiteBalance: String,
    val auto: String,
    val asShot: String,
    val donorWb: String,
    val lens: String,
    val distortionModel: String,
    val nativeMatch: String,
    val legacyInBounds: String,
    val distortion: String,
    val isoPolicy: String,
    val isoNearest: String,
    val isoHnnrStable: String,
    val isoCapture: String,
    val chromaticAberration: String,
    val vignetting: String,
    val convert: String,
    val preparing: String,
    val cancel: String,
    val open: String,
    val ready: String,
    val queued: String,
    val copying: String,
    val converting: String,
    val verifying: String,
    val saving: String,
    val complete: String,
    val failed: String,
    val cancelled: String,
    val activity: String,
    val noActivity: String,
    val advanced: String,
    val sensorMapping: String,
    val adaptive: String,
    val d65: String,
    val identity: String,
    val preview: String,
    val source: String,
    val donorPreview: String,
    val donorLens: String,
    val neutralize: String,
    val preserve: String,
    val inverseCalibration: String,
    val close: String,
)

fun copy(language: Language): ProductCopy = if (language == Language.ZH) {
    ProductCopy(
        settings = "设置",
        chooseRaf = "选择 RAF",
        replaceRaf = "更换 RAF",
        sourceHint = "GFX100RF 原始文件",
        donor = "X2D 100C 基准",
        donorMissing = "尚未设置",
        chooseDonor = "选择 3FR 基准",
        bundledSanitized = "内置净化 X2D 基准",
        useBundled = "恢复内置基准",
        whiteBalance = "白平衡",
        auto = "富士自动",
        asShot = "拍摄值",
        donorWb = "基准值",
        lens = "镜头校正",
        distortionModel = "畸变模型",
        nativeMatch = "原生匹配",
        legacyInBounds = "旧版无空边",
        distortion = "畸变",
        isoPolicy = "ISO 映射",
        isoNearest = "邻近 X2D",
        isoHnnrStable = "HNNR 稳定",
        isoCapture = "保留拍摄值",
        chromaticAberration = "色散",
        vignetting = "暗角",
        convert = "转换并保存 3FR",
        preparing = "准备中",
        cancel = "取消",
        open = "打开 3FR",
        ready = "可以转换",
        queued = "等待开始",
        copying = "读取文件",
        converting = "转换 RAW",
        verifying = "校验 3FR",
        saving = "保存文件",
        complete = "转换完成",
        failed = "转换失败",
        cancelled = "已取消",
        activity = "本次转换",
        noActivity = "选择 RAF 后即可开始",
        advanced = "高级设置",
        sensorMapping = "传感器映射",
        adaptive = "白平衡自适应",
        d65 = "固定 D65",
        identity = "不映射",
        preview = "预览图",
        source = "富士预览",
        donorPreview = "基准预览",
        donorLens = "基准镜头处理",
        neutralize = "移除",
        preserve = "保留",
        inverseCalibration = "反向 X2D 校准",
        close = "完成",
    )
} else {
    ProductCopy(
        settings = "Settings",
        chooseRaf = "Choose RAF",
        replaceRaf = "Replace RAF",
        sourceHint = "GFX100RF original",
        donor = "X2D 100C reference",
        donorMissing = "Not configured",
        chooseDonor = "Choose 3FR reference",
        bundledSanitized = "Bundled sanitized X2D reference",
        useBundled = "Use bundled reference",
        whiteBalance = "White balance",
        auto = "Fuji Auto",
        asShot = "As Shot",
        donorWb = "Reference",
        lens = "Lens correction",
        distortionModel = "Distortion model",
        nativeMatch = "Native match",
        legacyInBounds = "Legacy no-blank-edge",
        distortion = "Distortion",
        isoPolicy = "ISO mapping",
        isoNearest = "Nearest X2D",
        isoHnnrStable = "HNNR stable",
        isoCapture = "Preserve capture",
        chromaticAberration = "Lateral CA",
        vignetting = "Vignetting",
        convert = "Convert & Save 3FR",
        preparing = "Preparing",
        cancel = "Cancel",
        open = "Open 3FR",
        ready = "Ready to convert",
        queued = "Waiting to start",
        copying = "Reading files",
        converting = "Converting RAW",
        verifying = "Verifying 3FR",
        saving = "Saving file",
        complete = "Conversion complete",
        failed = "Conversion failed",
        cancelled = "Cancelled",
        activity = "Current conversion",
        noActivity = "Choose a RAF to begin",
        advanced = "Advanced",
        sensorMapping = "Sensor mapping",
        adaptive = "WB adaptive",
        d65 = "Fixed D65",
        identity = "Identity",
        preview = "Preview",
        source = "Fuji preview",
        donorPreview = "Reference preview",
        donorLens = "Reference lens handling",
        neutralize = "Remove",
        preserve = "Preserve",
        inverseCalibration = "Inverse X2D calibration",
        close = "Done",
    )
}
